# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mytestrepo',
                'doc_host': 'https://akrishnamo.github.io',
                'git_url': 'https://github.com/akrishnamo/mytestrepo',
                'lib_path': 'mytestrepo'},
  'syms': {'mytestrepo.bore': {'mytestrepo.bore.foo': ('core.html#foo', 'mytestrepo/bore.py')}}}
